### ISSUE TITLE
远程操控拨打座机电话和家用电器控制

### ISSUE THREAD

**Issue by linux0ne** [knownsec/gsm#1]
1、看了freebuf上的《探针盒子不用怕》的文章，很详实，很解渴，追到这里。
2、跟这个项目有关，也跟文章中的描述有关，有两个问题想请教如何开展：

一、家里有一部座机电话，号码为1234567。人在外，想用手机通过某种方式（目前看raspberry pi or ardinuo）实现，手机发送指令，激活家里的座机电话自动拨出号码 ，在对方的手机上或者是座机上显得是我家里的座机电话号码。   这种方式有没有什么可以指教的方案，或者是作品？

二、“探针”文章中提到可以用raspberrypi实现家里的电器的物联网，这方面我有极大的兴趣，期待您的进一步更新，因为您这儿看上去专业、详实、解渴。如果可能，我愿意参与其中。

注：目前我有一块第二代的树莓派，256M内存，B型。

**Comment by CloudnuY** [comment]
继电器控制电话通断，用树莓派模拟 DTMF 播出号码

也可参考 https://iotbytes.wordpress.com/send-dtmf-tones-with-raspberry-pi/

**Comment by linux0ne** [comment]
@CloudnuY 朋友你好！首先感谢你的回复，对我帮助很大，尤其是那个链接。这里有几个问题，想与您深入探讨：
一、我英文不是太好，不是学这个语种的，通过翻译软件，大概看懂了这个链接里的内容：它是通过在python脚本里设置一个号码，如13933994488（文章里并没有交待是否可以为手机号），然后通过运行这个脚本，脚本就会通过USB猫儿拨打与pi连接的座机电话，座机电话呼叫的“对方号码”就是这个13933994488，是这个意思么？

二、而为了实现远程操作功能，就需要我们能够通过网络或其他方式登入到pi中，启动并执行这个python脚本，继而实现上一步的功能，是这样么？

三、文章中关于这个DTMF的部分，专业性比较强，我没有看懂，我是不是只要将这个python脚本下载下来运行就可以了，它默认是调整好的么？

四、 USRobotics USR5637 USB Dial-up Modem这个硬件，在易趣上倒是比较便宜，但是在国内某宝上，都在500块以上，请问依您的经验，这样的设备有便宜的可替代的产品以？

五、您在回复中提到的“用继电器控制电话通断”是不是就是指用这个USB猫和DTMF指令进行控制？从我的需求来看，还需要单独连接一个断电器硬件么？

六、期待您的回复，如果不嫌弃我的愚笨，我留下我的微信：crack_886，可否成为好友，向您学习。

**Comment by rungobier** [comment]
@CloudnuY  的这个不错，基本上是可以实现拨打座机的效果，
因为平时工作比较忙，所以控制家里的IoT设备这块进展的比较慢，目前正在搞这块的代码。

**Comment by Lipingchang** [comment]
这个Modem淘宝已经800了。。
