### ISSUE TITLE
大哥 谢谢先。有没有思路实现远程拨打电话的远程遥控发短信的功能？

### ISSUE THREAD

**Issue by ffllc** [knownsec/gsm#2]
现在能实现查看收到的短信。请问有没有可能实现远控控制发短信，比如qq的验证码有的时候要求你发送指定内容到知道号码来验证。
还有就是远程通话的功能，我目前是通话来电转移实现接电话，但是有没有可能可以远程控制拨号，有的时候银行要求指定的去电手机才能提供服务。谢谢

**Comment by rungobier** [comment]
别急，平时工作很忙，回控的需求其实已经实现了，包括语音识别和指令扩展。
